### ISSUE TITLE
Incomplete generation of models

### ISSUE THREAD

**Issue by knowlecules** [cadrogui/sails-generator-automodel#2]
Had to generate models for about a dozen tables, maybe a hundred fields and only half of the models were created. Doubled the timeout https://github.com/cadrogui/sails-generator-automodel/blob/master/lib/autogen.js#L114
and all the fields went through.

Thanks btw. Even with the debugging it probably saved me an hour or two.

**Comment by cadrogui** [comment]
Him thanks for your comments, currently I'm working in a promised based version el this generator.

regards.
